 const bollywood =  [

    {    
        id: 1,
        category: "bollywood",
        img: "https://upload.wikimedia.org/wikipedia/en/8/80/Dilwale_Dulhania_Le_Jayenge_poster.jpg",
        title: "Dilwale Dulhania Le Jayenge",
        para: "Yashvardhan Raichand is a snobbish man, he breaks ties with his elder son Rahul, for marrying a girl with lower social status. When his younger son Rohan returns home, he is upset to know that his brother no longer lives with them. Rohan decides to reunite his family and goes to London and finds Rahul. But, the question is will he be successful in convincing his egoistic father for a reunion?",
        year: "14 December 2001",
        
      },
      {    
        id: 2,
        category: "bollywood",
        img: "https://upload.wikimedia.org/wikipedia/en/b/b6/Lagaan.jpg",
        title: "Lagaan",
        para: "Yashvardhan Raichand is a snobbish man, he breaks ties with his elder son Rahul, for marrying a girl with lower social status. When his younger son Rohan returns home, he is upset to know that his brother no longer lives with them. Rohan decides to reunite his family and goes to London and finds Rahul. But, the question is will he be successful in convincing his egoistic father for a reunion?",
        year: "14 December 2001",
      },
      {    
        id: 3,
        category: "bollywood",
        img: "https://upload.wikimedia.org/wikipedia/en/d/db/Dil_Chahta_Hai.jpg",
        title: " Dil Chahta Hai",
        para: "Yashvardhan Raichand is a snobbish man, he breaks ties with his elder son Rahul, for marrying a girl with lower social status. When his younger son Rohan returns home, he is upset to know that his brother no longer lives with them. Rohan decides to reunite his family and goes to London and finds Rahul. But, the question is will he be successful in convincing his egoistic father for a reunion?",
        year: "14 December 2001",
      },
      {    
        id: 4,
        category: "bollywood",
        img: "https://upload.wikimedia.org/wikipedia/en/6/6a/Gangs_of_Wasseypur_poster.jpg",
        title: "Gangs of Wasseypur",
        para: "Yashvardhan Raichand is a snobbish man, he breaks ties with his elder son Rahul, for marrying a girl with lower social status. When his younger son Rohan returns home, he is upset to know that his brother no longer lives with them. Rohan decides to reunite his family and goes to London and finds Rahul. But, the question is will he be successful in convincing his egoistic father for a reunion?",
        year: "14 December 2001",
      },
      {    
        id: 5,
        category: "bollywood",
        img: "https://upload.wikimedia.org/wikipedia/en/0/08/Rang_De_Basanti_poster.jpg",
        title: "Rang De Basanti",
        para: "Shot primarily in New Delhi, Rang De Basanti was released globally on 20 January 2006. Upon release, the film broke all opening box office records in India",
        year: "20 January 2006",
      },
      {    
        id: 6,
        category: "bollywood",
        img: "https://upload.wikimedia.org/wikipedia/en/1/17/Zindagi_Na_Milegi_Dobara.jpg",
        title: "Zindagi Na Milegi Dobara",
        para: "The film's story follows three childhood friends, Arjun, Kabir, and Imran, who reunite for a three-week road trip. They set off to Spain and meet Laila, who falls in love with Arjun and helps him overcome his compulsion to work.",
        year: "15 July 2011",
      },
      {    
        id: 7,
        category: "bollywood",
        img: "https://upload.wikimedia.org/wikipedia/en/4/45/QueenMoviePoster7thMarch.jpg",
        title: "Queen",
        para: "Yashvardhan Raichand is a snobbish man, he breaks ties with his elder son Rahul, for marrying a girl with lower social status. When his younger son Rohan returns home, he is upset to know that his brother no longer lives with them. Rohan decides to reunite his family and goes to London and finds Rahul. But, the question is will he be successful in convincing his egoistic father for a reunion?",
        year: "14 December 2001",
      },
      {    
        id: 8,
        category: "bollywood",
        img: "https://upload.wikimedia.org/wikipedia/en/4/42/Bhaag_Milkha_Bhaag_poster.jpg",
        title: "Bhaag Milkha Bhaag",
        para: "Bhaag Milkha Bhaag was inspired by The Race of My Life,[9] an autobiography co-written by Singh and his daughter, Sonia Sanwalka.[10][11][12] Singh sold the film rights for one rupee and inserted a clause stating that a share of the profits would be given to the Milkha Singh Charitable Trust",
        year: "22 July 2013",
      },
      {    
        id: 9,
        category: "bollywood",
        img: "https://upload.wikimedia.org/wikipedia/en/1/13/Dhoom_2_%282006_film%29_poster.jpg",
        title: "Dhoom 2",
        para: "Dhoom 2 premiered on 24 November 2006 in India, where it received the widest release in Indian cinema history with over 1800 prints, and grossed over ₹1.5 billion, and was declared a blockbuster by Box Office India.",
        year: "24 November 2006",
      },
      {    
        id: 10,
        category: "bollywood",
        img: "https://upload.wikimedia.org/wikipedia/en/9/9f/Jab_We_Met_Poster.jpg",
        title: "Jab We Met",
        para: "The film fetched several awards, among which was a National Film Award for Best Female Playback Singer awarded to Shreya Ghoshal for the song Yeh Ishq Haaye, which remained a chartbuster for many weeks",
        year: "	25 October 2007",
      },
      {    
          id: 11,
          category: "bollywood",
          img: "https://m.media-amazon.com/images/M/MV5BOTQ5Nzc3NzAtMzZlMS00ZWJjLWIxMGMtNDU4ZTQ1NmNjMjc5XkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_.jpg",
          title: "KABHI KHUSHI KABHIE GHAM",
          para: "Yashvardhan Raichand is a snobbish man, he breaks ties with his elder son Rahul, for marrying a girl with lower social status. When his younger son Rohan returns home, he is upset to know that his brother no longer lives with them. Rohan decides to reunite his family and goes to London and finds Rahul. But, the question is will he be successful in convincing his egoistic father for a reunion?",
          year: "14 December 2001",
        },
        {
          id: 12,
          category: "bollywood",
          img: "https://upload.wikimedia.org/wikipedia/en/9/95/Krrish_poster.jpg",
          title: "KRRISH",
          para: "Krrish is the story of a simple village boy Krishna (Hrithik Roshan) who lives with his grandmother (Rekha) having lost his parents to misfortune. Krishna meets Priya (Priyanka Chopra) when she comes with her group for a trek from Singapore. Having fallen in love with her, he rushes to Singapore on being called by Priya who is trying to save her job by getting Krishna to Singapore and having him pull unnaturally jaw-dropping stunts - something he does regularly in his village. But when he reaches Singapore, the biggest truth of his life uncovers itself, transforming him into ``Krrish``, a gallany superhero. What is it that alters his life to an extent as this?",
          year: "23 June 2006",
        },
        {
          id: 13,
          category: "bollywood",
          img: "https://upload.wikimedia.org/wikipedia/en/9/90/Bang_Bang_%282014_Film%29.jpg",
          title: "BANG BANG",
          para: "A young bank receptionist gets mixed up with Rajveer Nanda, a man who has a mysterious background.",
          year: "2 October 2014",
        },
        {
          id: 14,
          category: "bollywood",
          img: "https://m.media-amazon.com/images/M/MV5BYmRiMmZmZGMtNjFhNi00MTIwLTlkNjQtNGM4ZTEzOWFmZmIwXkEyXkFqcGdeQXVyNTkzNDQ4ODc@._V1_FMjpg_UX1000_.jpg",
          title: "MUJHE DOSTHI KAROGE",
          para: '"What would you do if the one you loved was not actually the one you loved. What would you do if your best friend was in love with the one you love. What would you do if your best friends are sacrificing their love for you. Meet Raj (Hrithik Roshan), Pooja (Rani Mukerji) and Tina (Kareena Kapoor)- 3 best friends thrown into a situation that time, letters, love and separation have created for th',
          year: "9 August 2002",
        },
        {
          id: 15,
          category: "bollywood",
          img: "https://s3images.zee5.com/wp-content/uploads/sites/7/2022/01/Untitled-design-2022-01-26T151639.382.jpg",
          title: "AGNEEPATH",
          para: "A young boys father is lynched before his eyes fifteen years later he returns home for revenge.",
          year: "26 January 2012",
        },
        {
          id: 16,
          category: "bollywood",
          img: "https://pbs.twimg.com/media/Fd1D0-KaEAMU3Im?format=jpg&name=900x900",
          title: "VIKRAM VEDHA",
          para: "A tough police officer sets out to track down and kill an equally tough gangsters.",
          year: "30 September 2022",
        },
        {
          id: 17,
          category: "bollywood",
          img: "https://cdn.shopify.com/s/files/1/0969/9128/products/Pathan-ShahRukhKhan-BollywoodSuperhitHindiMoviePoster_ce29dea2-91e6-43b6-81cc-1e2e0a1c1ae0.jpg?v=1675251704",
          title: "Pathan",
          para: "Indian RAW agent Pathaan (Shah Rukh Khan) gets to know of a major impending attack against India, mounted by a mercenary group led by the ruthless enigma Jim (John Abraham), who has a history of his own.",
          year: "25 January 2023",
        },
        {
          id: 18,
          category: "bollywood",
          img: "https://w0.peakpx.com/wallpaper/712/382/HD-wallpaper-movie-war-2019-hrithik-roshan-tiger-shroff.jpg",
          title: "War",
          para: "An Indian soldier is assigned to eliminate his former mentor and he must keep his wits about him if he is to be successful in his mission; when the two men collide, it results in a barrage of battles and bullets.",
          year: "2 October 2019",
        },
        {
          id: 19,
          category: "bollywood",
          img: "https://www.kerala9.com/wp-content/uploads/2022/04/kgf-chapter-2-rocky-hd-images-001.jpg",
          title: "KGF",
          para: "Rocky, a young man, seeks power and wealth in order to fulfil a promise to his dying mother. His quest takes him to Mumbai, where he becomes involved with the notorious gold mafia.",
          year: "20 December 2018 ",
        },
//     {
// id : 1,
// url : "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEg8WmHTWqXuBHsK1s-FX4T9HclmyylKoncJiA0GHr3CxoH0sPTrv4pOC2GPwDdEUYymMLTkAXGw85W6QhtS6khHWwTitf9wUQP3KQbzkN7X73yrg53YDf9Lomc42slo4C0LgCjlSWP_YSEvOiazcxO0UaLx_-V0ScESmbCZGN0vn2b9RmcaSesl3jSjrA/s1423/Pathaan.png",
// type : "Bollywood",
// date : "Janary 24, 2023 ",
// about : "[RELEASE: 25 January 2023] The high-octane spy thriller 'PATHAAN' starring Shah Rukh Khan, Deepika Padukone and John Abraham, directed by Siddharth Anand is set to release on January 25, 2023. The action spectacle will be released in Hindi, Tamil and Telugu. ",
// title : "MOVIE: Pathaan "
// },
// {
//     id : 2,
//     url : "https://assets.gadgets360cdn.com/pricee/assets/product/202206/Phone-Bhoot-poster_1656409397.jpg",
//     type : "Bollywood",
//     date : "Janary 24, 2023",
//     about : "[RELEASE:  4 November 2022] Phone Bhoot is a 2022 Indian Hindi-language supernatural comedy film directed by Gurmmeet Singh and produced by Farhan Akhtar and Ritesh Sidhwani under the banner of Excel Entertainment. The film stars Katrina Kaif, Ishaan Khattar, and Siddhant Chaturvedi and Jackie Shroff.  " ,
//     title : " MOVIE: Phone Bhoot "
//     },
//     {
//         id : 3,
//         url : "https://media.newstrack.in/uploads/entertainment-news/bollywood-news/Apr/26/big_thumb/ALIA_626785cf272b4.JPG",
//         type : "Bollywood",
//         date : "25 February 2022",
//         title : "MOVIE: Gangubai Kathiawadi",
//         about : "[RELEASE: 25 February 2022]  Gangubai Kathiawadi is a 2022 Indian Hindi-language biographical crime drama film directed by Sanjay Leela Bhansali and produced by Bhansali and Jayantilal Gada. The film stars Alia Bhatt as the titular character with Ajay Devgn, Shantanu Maheshwari, Vijay Raaz, Indira Tiwari, Seema Pahwa and Varun Kapoor in pivotal roles. "
//         },
//     {
//         id : 4,
//         url : "https://m.media-amazon.com/images/M/MV5BMGNmNDIyNmItOTU4MC00ZmQzLWI2ODQtODhmOTZlMmY0M2E1XkEyXkFqcGdeQXVyMTI1NDEyNTM5._V1_FMjpg_UX1000_.jpg",
//         type : "Bollywood",
//         date : "Janary 24, 2023",
//         about : " [RELEASE: 14 October 2022]  Doctor G is a 2022 Indian Hindi-language comedy-drama film directed by Anubhuti Kashyap and produced by Junglee Pictures. It stars Ayushmann Khurrana, Rakul Preet Singh and Shefali Shah. The film follows the struggles of a male doctor who is interested in orthopaedics but instead becomes a gynaecologist, and the ensuing chaos.",
//         title : "MOVIE:  Doctor G "
//         }

]

module.exports = bollywood;